**SQL02**

In [ ]:
# Importa a biblioteca pandasql
from pandasql import sqldf

In [ ]:
# IMPORTAÇÃO DAS BIBLIOTECAS

import pandas as pd
import numpy as np

# Configurações de visualização
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)


# FUNÇÕES PARA CARREGAMENTO E ANÁLISE DE DADOS

def load_and_display_data(file_path):
    """Carrega o CSV em um DataFrame e exibe informações iniciais."""
    print(f"Carregando dados de: {file_path}")
    # Explicitly set header=None as the first row of data seems to be incorrectly used as header
    df = pd.read_csv(file_path, header=None)

    # Assign column names based on the assumed structure from the context
    column_names = [
        'id', 'idade', 'sexo', 'dependentes', 'escolaridade',
        'estado_civil', 'limite_credito', 'valor_transacao_total_12m',
        'qtd_transacoes_12m'
    ]
    df.columns = column_names

    print("\nPrimeiras linhas:")
    display(df.head())

    print("\nInformações gerais:")
    df.info()

    print("\nEstatísticas descritivas:")
    display(df.describe())

    return df

def display_all_records(df):
    """Consulta 1: Visualiza todos os registros.
    Equivalente ao: SELECT * FROM clientes"""
    print("\nCONSULTA 1: Todos os registros")
    display(df)

def get_male_clients_by_age(df):
    """Consulta 2: Clientes masculinos ordenados por idade.
    Equivalente ao:
    SELECT id, idade, limite_credito
    FROM clientes
    WHERE sexo='M'
    ORDER BY idade DESC
    """
    clientes_masculinos = (
        df[df['sexo'] == 'M']
        [['id', 'idade', 'limite_credito']]
        .sort_values(by='idade', ascending=False)
    )
    print("\nCONSULTA 2: Clientes masculinos ordenados por idade:")
    display(clientes_masculinos)
    return clientes_masculinos

def get_average_age_by_sex(df):
    """Consulta 3: Média de idade por sexo.
    Equivalente ao:
    SELECT sexo, AVG(idade)
    FROM clientes
    GROUP BY sexo
    """
    media_idade = (
        df.groupby('sexo')['idade']
        .mean()
        .round(0)
        .astype(int)
        .reset_index()
    )
    media_idade.columns = ['sexo', 'media_idade']
    print("\nCONSULTA 3: Média de idade por sexo:")
    display(media_idade)
    return media_idade

def analyze_extra_metrics(df):
    """Realiza análises extras sobre o DataFrame."""
    print("\nANÁLISES EXTRAS")

    print("\nQuantidade de clientes por sexo:")
    display(df['sexo'].value_counts())

    print("\nLimite de crédito médio por sexo:")
    display(
        df.groupby('sexo')['limite_credito']
        .mean()
        .round(2)
    )

    print("\nQuantidade média de transações por sexo:")
    display(
        df.groupby('sexo')['qtd_transacoes_12m']
        .mean()
        .round(2)
    )

    print("\nTop 10 maiores limites de crédito:")
    display(
        df[['id','sexo','idade','limite_credito']]
        .sort_values('limite_credito', ascending=False)
        .head(10)
    )


# FLUXO PRINCIPAL DE EXECUÇÃO

# Substitua pelo nome do arquivo caso necessário
file_name = 'SQL para análise de dados M1 Exercício credito-aula.csv'

df_credito = load_and_display_data(file_name)

if df_credito is not None:
    display_all_records(df_credito)
    get_male_clients_by_age(df_credito)
    get_average_age_by_sex(df_credito)
    analyze_extra_metrics(df_credito)

print("\nAnálise concluída com sucesso!")

Carregando dados de: SQL para análise de dados M1 Exercício credito-aula.csv

Primeiras linhas:

,id,idade,sexo,dependentes,escolaridade,estado_civil,limite_credito,valor_transacao_total_12m,qtd_transacoes_12m
0,768805383,45,M,3,ensino medio,blue,12691.51,1144.90,42
1,818770008,49,F,5,mestrado,solteiro,8256.96,1291.45,33
2,713982108,51,M,3,mestrado,casado,3418.56,1887.72,20

Informações gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         3 non-null      int64
 1   idade                      3 non-null      int64
 2   sexo                       3 non-null      object
 3   dependentes                3 non-null      int64
 4   escolaridade               3 non-null      object
 5   estado_civil               3 non-null      object
 6   limite_credito             3 non-null      float64
 7   valor_transacao_total_12m  3 non-null      float64
 8   qtd_transacoes_12m         3 non-null      int64
dtypes: float64(2), int64(4), object(3)
memory usage: 348.0+ bytes

Estatísticas descritivas:

,id,idade,dependentes,limite_credito,valor_transacao_total_12m,qtd_transacoes_12m
count,3.000000e+00,3.000000,3.000000,3.000000,3.000000,3.000000
mean,7.671858e+08,48.333333,3.666667,8122.343333,1441.356667,31.666667
std,5.241272e+07,3.055050,1.154701,4637.940455,393.445542,11.060440
min,7.139821e+08,45.000000,3.000000,3418.560000,1144.900000,20.000000
25%,7.413937e+08,47.000000,3.000000,5837.760000,1218.175000,26.500000
50%,7.688054e+08,49.000000,3.000000,8256.960000,1291.450000,33.000000
75%,7.937877e+08,50.000000,4.000000,10474.235000,1589.585000,37.500000
max,8.187700e+08,51.000000,5.000000,12691.510000,1887.720000,42.000000

CONSULTA 1: Todos os registros

,id,idade,sexo,dependentes,escolaridade,estado_civil,limite_credito,valor_transacao_total_12m,qtd_transacoes_12m
0,768805383,45,M,3,ensino medio,blue,12691.51,1144.90,42
1,818770008,49,F,5,mestrado,solteiro,8256.96,1291.45,33
2,713982108,51,M,3,mestrado,casado,3418.56,1887.72,20

CONSULTA 2: Clientes masculinos ordenados por idade:

          id  idade  limite_credito
2  713982108     51         3418.56
0  768805383     45        12691.51

CONSULTA 3: Média de idade por sexo:

  sexo  media_idade
0    F           49
1    M           48

ANÁLISES EXTRAS

Quantidade de clientes por sexo:

sexo
M    2
F    1
Name: count, dtype: int64

Limite de crédito médio por sexo:

sexo
F    8256.96
M    8055.04
Name: limite_credito, dtype: float64

Quantidade média de transações por sexo:

sexo
F    33.0
M    31.0
Name: qtd_transacoes_12m, dtype: float64

Top 10 maiores limites de crédito:

          id sexo  idade  limite_credito
0  768805383    M     45        12691.51
1  818770008    F     49         8256.96
2  713982108    M     51         3418.56

Análise concluída com sucesso!

In [ ]:
!pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=91ed2565754b9790f4ca0619a5a360ffa71a0bacf046413e50f5bb0a114bdf88
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

Para realizar consultas SQL, definimos uma função auxiliar `pysqldf` que executa a consulta no contexto do DataFrame `df_credito`.

In [ ]:
pysqldf = lambda q: sqldf(q, globals())

### CONSULTA 1 (SQL): Visualizar todos os registros
Equivalente ao: `SELECT * FROM df_credito`

In [ ]:
query_all_records = """
SELECT *
FROM df_credito
"""

print("\nCONSULTA 1 (SQL): Todos os registros")
display(pysqldf(query_all_records))

CONSULTA 1 (SQL): Todos os registros

,id,idade,sexo,dependentes,escolaridade,estado_civil,limite_credito,valor_transacao_total_12m,qtd_transacoes_12m
0,768805383,45,M,3,ensino medio,blue,12691.51,1144.90,42
1,818770008,49,F,5,mestrado,solteiro,8256.96,1291.45,33
2,713982108,51,M,3,mestrado,casado,3418.56,1887.72,20

### CONSULTA 2 (SQL): Clientes masculinos ordenados por idade
Equivalente ao:

```sql
SELECT id, idade, limite_credito
FROM df_credito
WHERE sexo='M'
ORDER BY idade DESC
```

In [ ]:
query_male_clients = """
SELECT id, idade, limite_credito
FROM df_credito
WHERE sexo = 'M'
ORDER BY idade DESC
"""

print("\nCONSULTA 2 (SQL): Clientes masculinos ordenados por idade:")
display(pysqldf(query_male_clients))

CONSULTA 2 (SQL): Clientes masculinos ordenados por idade:

          id  idade  limite_credito
0  713982108     51         3418.56
1  768805383     45        12691.51

### CONSULTA 3 (SQL): Média de idade por sexo
Equivalente ao:

```sql
SELECT sexo,
       AVG(idade) as media_idade
FROM df_credito
GROUP BY sexo
```

In [ ]:
query_avg_age_by_sex = """
SELECT sexo,
       CAST(ROUND(AVG(idade), 0) AS INT) AS media_idade
FROM df_credito
GROUP BY sexo
"""

print("\nCONSULTA 3 (SQL): Média de idade por sexo:")
display(pysqldf(query_avg_age_by_sex))

CONSULTA 3 (SQL): Média de idade por sexo:

  sexo  media_idade
0    F           49
1    M           48

### ANÁLISES EXTRAS (SQL)

In [ ]:
query_clients_by_sex = """
SELECT sexo, COUNT(id) as quantidade_clientes
FROM df_credito
GROUP BY sexo
"""

print("\nQuantidade de clientes por sexo:")
display(pysqldf(query_clients_by_sex))

Quantidade de clientes por sexo:

  sexo  quantidade_clientes
0    F                    1
1    M                    2

In [ ]:
query_avg_credit_limit = """
SELECT sexo, ROUND(AVG(limite_credito), 2) as limite_credito_medio
FROM df_credito
GROUP BY sexo
"""

print("\nLimite de crédito médio por sexo:")
display(pysqldf(query_avg_credit_limit))

Limite de crédito médio por sexo:

  sexo  limite_credito_medio
0    F               8256.96
1    M               8055.04

In [ ]:
query_avg_transactions = """
SELECT sexo, ROUND(AVG(qtd_transacoes_12m), 2) as media_transacoes
FROM df_credito
GROUP BY sexo
"""

print("\nQuantidade média de transações por sexo:")
display(pysqldf(query_avg_transactions))

Quantidade média de transações por sexo:

  sexo  media_transacoes
0    F              33.0
1    M              31.0

In [ ]:
query_top_10_credit = """
SELECT id, sexo, idade, limite_credito
FROM df_credito
ORDER BY limite_credito DESC
LIMIT 10
"""

print("\nTop 10 maiores limites de crédito:")
display(pysqldf(query_top_10_credit))

Top 10 maiores limites de crédito:

          id sexo  idade  limite_credito
0  768805383    M     45        12691.51
1  818770008    F     49         8256.96
2  713982108    M     51         3418.56