# **Módulo 3 | SQL: Selecionando & Ordenando**
## Notebook corrigido para rodar no Google Colab

Este notebook não usa AWS nem upload de arquivo.  
Ele recria a tabela `transacoes` dentro do próprio Colab usando SQLite e executa as queries pedidas pela atividade.

## 1. Preparação dos dados

In [ ]:

import pandas as pd
import sqlite3

# Dados do exercício M3 - transacoes
transacoes = pd.DataFrame({
    "id_cliente":   [1, 2, 3, 1, 1, 3, 4, 5, 3],
    "id_transacao": [768805383, 768805399, 818770008, 76856563, 767573759, 818575758, 764545534, 76766789, 8154567758],
    "valor":        [50.74, 30.90, 110.00, 2000.90, 15.70, 2.99, 50.74, 10.00, 1100.00],
    "id_loja":      ["magalu", "giraffas", "postoshell", "magalu", "subway", "seveneleven", "extra", "subway", "shopee"]
})

# Cria banco SQLite em memória para simular as consultas SQL
con = sqlite3.connect(":memory:")
transacoes.to_sql("transacoes", con, index=False, if_exists="replace")

print("✅ Tabela 'transacoes' criada com sucesso!")
print(f"{len(transacoes)} linhas carregadas.")
display(transacoes)

✅ Tabela 'transacoes' criada com sucesso!
9 linhas carregadas.

   id_cliente  id_transacao    valor      id_loja
0           1     768805383    50.74       magalu
1           2     768805399    30.90     giraffas
2           3     818770008   110.00   postoshell
3           1      76856563  2000.90       magalu
4           1     767573759    15.70       subway
5           3     818575758     2.99  seveneleven
6           4     764545534    50.74        extra
7           5      76766789    10.00       subway
8           3    8154567758  1100.00       shopee

## 2. Query 1 — visualizar todos os dados

In [ ]:

# Query 1
# SELECT * FROM transacoes

query1 = pd.read_sql_query("""
SELECT *
FROM transacoes
""", con)

display(query1)
query1.to_csv("query1.csv", index=False)
print("✅ Arquivo query1.csv salvo")

   id_cliente  id_transacao    valor      id_loja
0           1     768805383    50.74       magalu
1           2     768805399    30.90     giraffas
2           3     818770008   110.00   postoshell
3           1      76856563  2000.90       magalu
4           1     767573759    15.70       subway
5           3     818575758     2.99  seveneleven
6           4     764545534    50.74        extra
7           5      76766789    10.00       subway
8           3    8154567758  1100.00       shopee

✅ Arquivo query1.csv salvo

## 3. Query 2 — usar alias `AS`

In [ ]:

# Query 2
# SELECT id_cliente, valor, id_loja AS nome_loja FROM transacoes;

query2 = pd.read_sql_query("""
SELECT id_cliente, valor, id_loja AS nome_loja
FROM transacoes
""", con)

display(query2)
query2.to_csv("query2.csv", index=False)
print("✅ Arquivo query2.csv salvo")

   id_cliente    valor    nome_loja
0           1    50.74       magalu
1           2    30.90     giraffas
2           3   110.00   postoshell
3           1  2000.90       magalu
4           1    15.70       subway
5           3     2.99  seveneleven
6           4    50.74        extra
7           5    10.00       subway
8           3  1100.00       shopee

✅ Arquivo query2.csv salvo

## 4. Query 3 — lojas sem repetição com `DISTINCT`

In [ ]:

# Query 3
# SELECT DISTINCT id_loja AS nome_loja FROM transacoes;

query3 = pd.read_sql_query("""
SELECT DISTINCT id_loja AS nome_loja
FROM transacoes
""", con)

display(query3)
query3.to_csv("query3.csv", index=False)
print("✅ Arquivo query3.csv salvo")

     nome_loja
0       magalu
1     giraffas
2   postoshell
3       subway
4  seveneleven
5        extra
6       shopee

✅ Arquivo query3.csv salvo

## 5. Query 4 — ordenar e limitar resultados

In [ ]:

# Query 4
# SELECT id_cliente, valor FROM transacoes ORDER BY valor DESC LIMIT 2;

query4 = pd.read_sql_query("""
SELECT id_cliente, valor
FROM transacoes
ORDER BY valor DESC
LIMIT 2
""", con)

display(query4)
query4.to_csv("query4.csv", index=False)
print("✅ Arquivo query4.csv salvo")

   id_cliente   valor
0           1  2000.9
1           3  1100.0

✅ Arquivo query4.csv salvo

## 6. Conferência final

In [ ]:

# Conferência final
import os

arquivos = ["query1.csv", "query2.csv", "query3.csv", "query4.csv"]

print("Arquivos gerados:")
for arquivo in arquivos:
    print(f" - {arquivo}: {'OK' if os.path.exists(arquivo) else 'ERRO'}")

print("\n🎉 M3 concluído! Agora compartilhe o link deste Colab na EBAC.")

Arquivos gerados:
 - query1.csv: OK
 - query2.csv: OK
 - query3.csv: OK
 - query4.csv: OK

🎉 M3 concluído! Agora compartilhe o link deste Colab na EBAC.